'02035
Option Explicit


Const wdFindContinue = 1
'set view
Private Sub Workbook_Open()
    wsData.Activate
    ActiveWindow.Zoom = 120
End Sub

'notes
'supports max 4 leadership positions and max 4 professional experiences
'supports max 3 bullet points for each position

'necessary improvements
'   TRIM responses
'only add a new line if content is added
'   applies to phone/email and address, and potentially other places - BUGPOT154262

'overall expansion prospects
'   multiple resume style
'   check if the resume is over 1 page
'       offer different options to try to fit to one page
'           change margins, font size
'   Validation/manipulation for phone number format



Sub resumeBuilder()
'ActiveWindow.Zoom = 120
Dim newThru As Byte
newThru = 0
Dim complete As Byte
complete = 0
Dim multiPageMsg As String

'HEADER CONTENT
Dim fName As String, mName As String, lName As String
'requires validation for mName if initialOption is chosen
'   remove period if it is entered
'   add period

Dim addressOne As String, addressTwo As String
Dim addTypeOne As String, addTypeTwo As String, strAddress As String
'may require validation and/or manipulation

Dim phoneOne As String, phoneTwo As String, email As String
Dim phoneTypeOne As String, phoneTypeTwo As String
'may require validation and/or manipulation
Dim strPhoneEmail As String

Dim headerContentOne As String, headerContentTwo As String, headerContentThree As String
Dim strHeaderContent As String, summary As String

'EDUCATION
Dim uniName As String, schoolName As String, uniCity As String, uniState As String, uniLoc As String
Dim majorOne As String, majorTwo As String, degType As String, combMajor As String
Dim gradMonth As String, gradYear As String, gradDate As String
Dim GPA As String, majGPA As String, combGPA As String
Dim binBothGPA As Byte, binExpected As Byte, binDoubleMaj As Byte
Dim courses As String, awards As String, edContentOne As String, edContentTwo As String, SAT As String, ACT As String
Dim colCount As Integer, colWordCount As Long

'LEADERSHIP EXPERIENCE
Dim LEtitleOne As String, LEtitleTwo As String, LEtitleThree As String, LEtitleFour As String
Dim LEorgOne As String, LEorgTwo As String, LEorgThree As String, LEorgFour As String
Dim LEcityOne As String, LEcityTwo As String, LEcityThree As String, LEcityFour As String
Dim LEstateOne As String, LEstateTwo As String, LEstateThree As String, LEstateFour As String
Dim LElocOne As String, LElocTwo As String, LElocThree As String, LElocFour As String
Dim LEstartMoOne As String, LEstartMoTwo As String, LEstartMoThree As String, LEstartMoFour As String
Dim LEendMoOne As String, LEendMoTwo As String, LEendMoThree As String, LEendMoFour As String
Dim LEstartYrOne As String, LEstartYrTwo As String, LEstartYrThree As String, LEstartYrFour As String
Dim LEendYrOne As String, LEendYrTwo As String, LEendYrThree As String, LEendYrFour As String
Dim LEdateRangeOne As String, LEdateRangeTwo As String, LEdateRangeThree As String, LEdateRangeFour As String
Dim LEcontentOneA As String, LEcontentOneB As String, LEcontentOneC As String
Dim LEcontentTwoA As String, LEcontentTwoB As String, LEcontentTwoC As String
Dim LEcontentThreeA As String, LEcontentThreeB As String, LEcontentThreeC As String
Dim LEcontentFourA As String, LEcontentFourB As String, LEcontentFourC As String


'PROFESSIONAL EXPERIENCE
Dim PEtitleOne As String, PEtitleTwo As String, PEtitleThree As String, PEtitleFour As String
Dim PEorgOne As String, PEorgTwo As String, PEorgThree As String, PEorgFour As String
Dim PEcityOne As String, PEcityTwo As String, PEcityThree As String, PEcityFour As String
Dim PEstateOne As String, PEstateTwo As String, PEstateThree As String, PEstateFour As String
Dim PElocOne As String, PElocTwo As String, PElocThree As String, PElocFour As String
Dim PEstartMoOne As String, PEstartMoTwo As String, PEstartMoThree As String, PEstartMoFour As String
Dim PEendMoOne As String, PEendMoTwo As String, PEendMoThree As String, PEendMoFour As String
Dim PEstartYrOne As String, PEstartYrTwo As String, PEstartYrThree As String, PEstartYrFour As String
Dim PEendYrOne As String, PEendYrTwo As String, PEendYrThree As String, PEendYrFour As String
Dim PEdateRangeOne As String, PEdateRangeTwo As String, PEdateRangeThree As String, PEdateRangeFour As String
Dim PEcontentOneA As String, PEcontentOneB As String, PEcontentOneC As String
Dim PEcontentTwoA As String, PEcontentTwoB As String, PEcontentTwoC As String
Dim PEcontentThreeA As String, PEcontentThreeB As String, PEcontentThreeC As String
Dim PEcontentFourA As String, PEcontentFourB As String, PEcontentFourC As String

'SKILLS & INTERESTS
Dim listTitleOne As String, listTitleTwo As String, listTitleThree As String, listTitleFour As String, listTitleFive As String, listTitleSix As String, listTitleSeven As String
Dim listOne As String, listTwo As String, listThree As String, listFour As String, listFive As String, listSix As String, listSeven As String



'create and open new Word file
Dim wrdApp As Object, wrdDoc As Object
Dim i As Integer
Dim lineWidth As Long
Dim nPages As Integer
Dim response As String

Set wrdApp = CreateObject("Word.Application")
'wrdApp.Visible = True
'wrdApp.Activate
Set wrdDoc = wrdApp.Documents.Add

'set margins

    With wrdApp.ActiveDocument.PageSetup
        .RightMargin = 50
        .LeftMargin = 50
        .TopMargin = 25
        .BottomMargin = 25
        lineWidth = .PageWidth - .LeftMargin - .RightMargin
    End With



'delete the file if it already exists
'With wrdDoc
'    If Dir("C:\Documents\****.doc") <> "" Then
'        Kill "C:\Documents\****.doc"
'    End If
'End With





'NAME
With wsData
    fName = .Range("fName")
    mName = .Range("mName")
    lName = .Range("lName")
End With

With wrdApp.Selection
    
    'center
    With .ParagraphFormat
        .Alignment = 1
        .SpaceAfter = 0
    End With
    
    With .Font
        .Name = "Times New Roman"
        .Bold = True
        .Size = 22
    End With
    
End With

'enter content
wrdApp.Selection.TypeText Text:=fName & " " & mName & " " & lName
'new line
wrdApp.Selection.TypeParagraph




'ADDRESS
With wsData
    addressOne = .Range("addressOne")
    addTypeOne = .Range("addTypeOne")
    addressTwo = .Range("addressTwo")
    addTypeTwo = .Range("addTypeTwo")
End With

With wrdApp.Selection
    With .Font
        .Name = "Times New Roman"
        .Bold = False
        .Size = 9.5
    End With
End With



'line spacing
    With wrdApp.Selection.ParagraphFormat
        .SpaceAfter = 0
        .SpaceAfterAuto = False
        .LineSpacingRule = wdLineSpaceExactly
        .LineSpacing = 12
    End With



'determine address(es)
'may consider changing this to a case structure
If addressOne <> "" Then
    strAddress = addressOne
    If addTypeOne <> "" Or addressTwo <> "" Then
        If addTypeOne <> "" Then strAddress = addTypeOne & ": " & addressOne
        If addressTwo <> "" Then
            strAddress = strAddress & " | " & addressTwo
            If addTypeTwo <> "" Then
                strAddress = addTypeOne & ": " & addressOne & " | " & addTypeTwo & ": " & addressTwo
            End If
        End If
    End If
End If
'enter content
    wrdApp.Selection.TypeText Text:=strAddress

'new line - Only put a new line if content was added
    wrdApp.Selection.TypeParagraph




'PHONE NUMBER & EMAIL ADDRESS

'expansion
'   option to use phone types or not

With wsData
    phoneOne = .Range("phoneOne")
    phoneTypeOne = .Range("phoneTypeOne")
    phoneTwo = .Range("phoneTwo")
    phoneTypeTwo = .Range("phoneTypeTwo")
'requires validation or manipulation for formatting
    email = .Range("email")
End With




If phoneOne <> "" Then
    strPhoneEmail = phoneOne
    If phoneTypeOne <> "" Or phoneTwo <> "" Then
        If phoneTypeOne <> "" Then strPhoneEmail = phoneTypeOne & ": " & phoneOne
        If phoneTwo <> "" Then
            strPhoneEmail = strPhoneEmail & " | " & phoneTwo
            If phoneTypeTwo <> "" Then
                strPhoneEmail = phoneTypeOne & ": " & phoneOne & " | " & phoneTypeTwo & ": " & phoneTwo
            End If
        End If
    End If
ElseIf phoneTwo <> "" Then
    strPhoneEmail = phoneTwo
    If phoneTypeTwo <> "" Then strPhoneEmail = phoneTypeTwo & ": " & strPhoneEmail
End If

If strPhoneEmail <> "" Then
    If email <> "" Then strPhoneEmail = strPhoneEmail & " | " & email
Else
    strPhoneEmail = email
End If

'enter content
wrdApp.Selection.TypeText Text:=strPhoneEmail

'new line - Only put a new line if content was added
If strPhoneEmail <> "" Then
    wrdApp.Selection.TypeParagraph
End If






'ADDITIONAL CONTENT

'expansion
'   allow for headerContentTypes
'   allow for the option for headerContentTypes

headerContentOne = wsData.Range("headerContentOne")
headerContentTwo = wsData.Range("headerContentTwo")
headerContentThree = wsData.Range("headerContentThree")

If headerContentOne <> "" Then
    strHeaderContent = headerContentOne
End If

If headerContentTwo <> "" Then
    
    If headerContentOne <> "" Then
        headerContentTwo = " | " & headerContentTwo
    End If
    
    strHeaderContent = strHeaderContent & headerContentTwo
End If

If headerContentThree <> "" Then

    If headerContentOne <> "" Or headerContentTwo <> "" Then
        headerContentThree = " | " & headerContentThree
    End If

    strHeaderContent = strHeaderContent & headerContentThree
End If

'enter content
wrdApp.Selection.TypeText Text:=strHeaderContent

'new line
wrdApp.Selection.TypeParagraph







'SUMMARY SECTION
summary = wsData.Range("summary")

If summary <> "" Then
    'center
    With wrdApp.Selection
        .Font.Bold = True
        
        With .ParagraphFormat
            .Alignment = 1
            .SpaceAfter = 0
        End With
        
        .TypeParagraph
        .TypeText Text:="SUMMARY"
        
        With wrdApp.Selection
            .Characters(1).Borders.Enable = True
            
            With .ParagraphFormat
                .Borders(wdBorderBottom).lineWidth = wdLineWidth025pt
                .Borders(wdBorderTop).LineStyle = wdLineStyleNone
                .Borders(wdBorderRight).LineStyle = wdLineStyleNone
                .Borders(wdBorderLeft).LineStyle = wdLineStyleNone
            End With
            
        End With
        
        With wrdApp.Selection
            .TypeParagraph
            .Characters(1).Borders.Enable = False
            'align left
            .ParagraphFormat.Alignment = 0
            .Font.Size = 10
        End With
    
        .Font.Bold = False
        
        With .ParagraphFormat
            .Alignment = 0
            .SpaceAfter = 0
        End With
        
        .TypeText Text:=summary
        .TypeParagraph
        .TypeParagraph
        
    End With
Else: wrdApp.Selection.TypeParagraph
End If

With wrdApp.Selection.ParagraphFormat
    .Alignment = 1
    .SpaceAfter = 0
End With







'EDUCATION

wrdApp.Selection.Font.Bold = True
wrdApp.Selection.TypeText Text:="EDUCATION"

'add line
With wrdApp.Selection
    .Characters(1).Borders.Enable = True
    With .ParagraphFormat
        .Borders(wdBorderBottom).lineWidth = wdLineWidth025pt
        .Borders(wdBorderTop).LineStyle = wdLineStyleNone
        .Borders(wdBorderRight).LineStyle = wdLineStyleNone
        .Borders(wdBorderLeft).LineStyle = wdLineStyleNone
    End With
End With

wrdApp.Selection.TypeParagraph
With wrdApp.Selection
    .Characters(1).Borders.Enable = False
    'align left
    .ParagraphFormat.Alignment = 0
    .Font.Size = 10
End With

uniName = Range("uniName")
wrdApp.Selection.TypeText Text:=uniName

wrdApp.Selection.Font.Bold = False

uniCity = Range("uniCity")
uniState = Range("uniState")

uniLoc = uniCity & ", " & uniState
wrdApp.Selection.TypeText Text:=uniLoc
    
       
wrdApp.Selection.ParagraphFormat.TabStops.Add Position:=lineWidth, _
Alignment:=wdAlignTabRight, Leader:=0
wrdApp.Selection.MoveLeft Unit:=1, Count:=Len(uniLoc)
wrdApp.Selection.TypeText Text:=vbTab
wrdApp.Selection.MoveRight Unit:=1, Count:=Len(uniLoc)

'new line
wrdApp.Selection.TypeParagraph

schoolName = Range("schoolName")
wrdApp.Selection.Font.Bold = True
wrdApp.Selection.TypeText Text:=schoolName

wrdApp.Selection.Font.Bold = False
binExpected = 1
gradMonth = Range("gradMonth")
gradYear = Range("gradYear")
gradDate = gradMonth & " " & gradYear

If binExpected = 1 Then
    gradDate = "Expected " & gradDate
End If

With wrdApp.Selection
    .TypeText Text:=gradDate
    .MoveLeft Unit:=1, Count:=Len(gradDate)
    .TypeText Text:=vbTab
    .MoveRight Unit:=1, Count:=Len(gradDate)
End With

'new line
wrdApp.Selection.TypeParagraph

wrdApp.Selection.Font.Italic = True

binDoubleMaj = 0
If majorOne <> "" And majorTwo <> "" Then binDoubleMaj = 1

degType = Range("degType")
majorOne = Range("majorOne")
majorTwo = Range("majorTwo")

If binDoubleMaj = 1 Then
    combMajor = degType & " - " & majorOne & " and " & majorTwo & " (Double Major)"
Else
    combMajor = degType & " - " & majorOne
End If

wrdApp.Selection.TypeText Text:=combMajor



wrdApp.Selection.Font.Italic = False
GPA = Range("GPA")
majGPA = Range("majGPA")

If GPA <> "" And majGPA <> "" Then binBothGPA = 1

If binBothGPA = 1 Then
    combGPA = "Cumulative GPA: " & GPA & " | Major GPA: " & majGPA
Else
    If GPA <> "" Then
        combGPA = "GPA: " & GPA
    Else
        combGPA = "Major GPA: " & majGPA
    End If
End If

With wrdApp.Selection
    .TypeText Text:=combGPA
    .MoveLeft Unit:=1, Count:=Len(combGPA)
    .TypeText Text:=vbTab
    .MoveRight Unit:=1, Count:=Len(combGPA)
End With


'new line
wrdApp.Selection.TypeParagraph

courses = Range("courses")
awards = Range("awards")
edContentOne = Range("edContentOne")
edContentTwo = Range("edContentTwo")
SAT = Range("SAT")
ACT = Range("ACT")

'create bulletted list for edContent if there is any
If courses <> "" Or _
    awards <> "" Or _
    edContentOne <> "" Or _
    edContentTwo <> "" Or _
    SAT <> "" Or _
    ACT <> "" Then

    With wrdApp
        .ListGalleries(wdBulletGallery).ListTemplates(1).Name = ""
        .Selection.Range.ListFormat.ApplyListTemplate ListTemplate:=.ListGalleries(wdBulletGallery).ListTemplates(1), _
        continuepreviouslist:=False, applyto:=wdListApplyToWholeList, defaultlistbehavior:=wdWord9ListBehavior
    End With
    
    If SAT <> "" Then
        SAT = "SAT Score: " & SAT
        wrdApp.Selection.TypeText Text:=SAT
        wrdApp.Selection.TypeParagraph
        'colCount = colCount + 1
        'colWordCount = colWordCount + Len(SAT)
    End If
    
    If ACT <> "" Then
        ACT = "ACT Score: " & ACT
        wrdApp.Selection.TypeText Text:=ACT
        wrdApp.Selection.TypeParagraph
        'colCount = colCount + 1
        'colWordCount = colWordCount + Len(ACT)
    End If
    
    If courses <> "" Then
        wrdApp.Selection.TypeText Text:=courses
        wrdApp.Selection.TypeParagraph
        'colCount = colCount + 1
        'colWordCount = colWordCount + Len(courses)
    End If
    
    If awards <> "" Then
        wrdApp.Selection.TypeText Text:=awards
        wrdApp.Selection.TypeParagraph
        'colCount = colCount + 1
        'colWordCount = colWordCount + Len(awards)
    End If
    
    If edContentOne <> "" Then
        wrdApp.Selection.TypeText Text:=edContentOne
        wrdApp.Selection.TypeParagraph
        'colCount = colCount + 1
        'colWordCount = colWordCount + Len(edContentOne)
    End If
    
    If edContentTwo <> "" Then
        wrdApp.Selection.TypeText Text:=edContentTwo
        wrdApp.Selection.TypeParagraph
        'colCount = colCount + 1
        'colWordCount = colWordCount + Len(edContentTwo)
    End If
    
    'create 2 columns if 5 or more of the fields are filled out
'    If colCount > 4 Then
'
'        wrdApp.Selection.MoveUp Unit:=wdParagraph, Count:=colCount, Extend:=wdExtend
'
'        With wrdApp.Selection.PageSetup.TextColumns
'            .SetCount NumColumns:=2
'            .EvenlySpaced = True
'            .LineBetween = False
'            .Width = InchesToPoints(7.11)
'        End With
'
'    End If
    
    'end bulletted list
    wrdApp.Selection.Range.ListFormat.RemoveNumbers wdBulletGallery
    wrdApp.Selection.TypeParagraph
End If














'LEADERSHIP EXPERIENCE

With wrdApp.Selection
    .Font.Bold = True
    .TypeText Text:=UCase(wsData.Range("secOneTitle"))
    'center
    With .ParagraphFormat
        .Alignment = 1
        .SpaceAfter = 0
    End With
End With
    


'add line
With wrdApp.Selection
    .Characters(1).Borders.Enable = True
    With .ParagraphFormat
        .Borders(wdBorderBottom).lineWidth = wdLineWidth025pt
        .Borders(wdBorderTop).LineStyle = wdLineStyleNone
        .Borders(wdBorderRight).LineStyle = wdLineStyleNone
        .Borders(wdBorderLeft).LineStyle = wdLineStyleNone
    End With
    
    .TypeParagraph
End With

With wrdApp.Selection
    .Characters(1).Borders.Enable = False
    'align left
    .ParagraphFormat.Alignment = 0
    .Font.Size = 10
End With





'store variables
LEtitleOne = Range("LEtitleOne")
LEorgOne = Range("LEorgOne")
LEcityOne = Range("LEcityOne")
LEstateOne = Range("LEstateOne")
LEstartMoOne = Range("LEstartMoOne")
LEstartYrOne = Range("LEstartYrOne")
LEendMoOne = Range("LEendMoOne")
LEendYrOne = Range("LEendYrOne")
LEcontentOneA = Range("LEcontentOneA")
LEcontentOneB = Range("LEcontentOneB")
LEcontentOneC = Range("LEcontentOneC")

LEtitleTwo = Range("LEtitleTwo")
LEorgTwo = Range("LEorgTwo")
LEcityTwo = Range("LEcityTwo")
LEstateTwo = Range("LEstateTwo")
LEstartMoTwo = Range("LEstartMoTwo")
LEstartYrTwo = Range("LEstartYrTwo")
LEendMoTwo = Range("LEendMoTwo")
LEendYrTwo = Range("LEendYrTwo")
LEcontentTwoA = Range("LEcontentTwoA")
LEcontentTwoB = Range("LEcontentTwoB")
LEcontentTwoC = Range("LEcontentTwoC")

LEtitleThree = Range("LEtitleThree")
LEorgThree = Range("LEorgThree")
LEcityThree = Range("LEcityThree")
LEstateThree = Range("LEstateThree")
LEstartMoThree = Range("LEstartMoThree")
LEstartYrThree = Range("LEstartYrThree")
LEendMoThree = Range("LEendMoThree")
LEendYrThree = Range("LEendYrThree")
LEcontentThreeA = Range("LEcontentThreeA")
LEcontentThreeB = Range("LEcontentThreeB")
LEcontentThreeC = Range("LEcontentThreeC")

LEtitleFour = Range("LEtitleFour")
LEorgFour = Range("LEorgFour")
LEcityFour = Range("LEcityFour")
LEstateFour = Range("LEstateFour")
LEstartMoFour = Range("LEstartMoFour")
LEstartYrFour = Range("LEstartYrFour")
LEendMoFour = Range("LEendMoFour")
LEendYrFour = Range("LEendYrFour")
LEcontentFourA = Range("LEcontentFourA")
LEcontentFourB = Range("LEcontentFourB")
LEcontentFourC = Range("LEcontentFourC")

If LEstartMoOne <> "" Or _
    LEstartYrOne <> "" Or _
    LEendMoOne <> "" Or _
    LEendYrOne <> "" Then
        LEdateRangeOne = LEstartMoOne & " " & LEstartYrOne & " - " & LEendMoOne
        If LEendYrOne <> "" Then LEdateRangeOne = LEdateRangeOne & " " & LEendYrOne
End If

If LEstartMoTwo <> "" Or _
    LEstartYrTwo <> "" Or _
    LEendMoTwo <> "" Or _
    LEendYrTwo <> "" Then
        LEdateRangeTwo = LEstartMoTwo & " " & LEstartYrTwo & " - " & LEendMoTwo
        If LEendYrTwo <> "" Then LEdateRangeTwo = LEdateRangeTwo & " " & LEendYrTwo
End If

If LEstartMoThree <> "" Or _
    LEstartYrThree <> "" Or _
    LEendMoThree <> "" Or _
    LEendYrThree <> "" Then
        LEdateRangeThree = LEstartMoThree & " " & LEstartYrThree & " - " & LEendMoThree
        If LEendYrThree <> "" Then LEdateRangeThree = LEdateRangeThree & " " & LEendYrThree
End If

If LEstartMoFour <> "" Or _
    LEstartYrFour <> "" Or _
    LEendMoFour <> "" Or _
    LEendYrFour <> "" Then
        LEdateRangeFour = LEstartMoFour & " " & LEstartYrFour & " - " & LEendMoFour
        If LEendYrFour <> "" Then LEdateRangeFour = LEdateRangeFour & " " & LEendYrFour
End If

'LE POSITION ONE

If LEcityOne <> "" And LEstateOne <> "" Then

With wrdApp.Selection
    .TypeText Text:=LEtitleOne
    .Font.Bold = False
    
    
        LElocOne = LEcityOne & ", " & LEstateOne
        .TypeText Text:=LElocOne
    
    
        .ParagraphFormat.TabStops.Add Position:=lineWidth, _
            Alignment:=wdAlignTabRight, Leader:=0
        .MoveLeft Unit:=1, Count:=Len(LElocOne)
        .TypeText Text:=vbTab
        .MoveRight Unit:=1, Count:=Len(LElocOne)
    
        .TypeParagraph
    
        .Font.Italic = True
        .TypeText Text:=LEorgOne
        .Font.Italic = False
        .TypeText Text:=LEdateRangeOne
        .ParagraphFormat.TabStops.Add Position:=lineWidth, _
            Alignment:=wdAlignTabRight, Leader:=0
        .MoveLeft Unit:=1, Count:=Len(LEdateRangeOne)
        .TypeText Text:=vbTab
        .MoveRight Unit:=1, Count:=Len(LEdateRangeOne)
        .TypeParagraph
        
        
    With .ParagraphFormat
        .SpaceBefore = 0
        .SpaceBeforeAuto = False
        .SpaceAfter = 0
        .SpaceAfterAuto = False
        .LineSpacingRule = wdLineSpaceExactly
        .LineSpacing = 6
    End With
        
        .TypeParagraph
        .ParagraphFormat.LineSpacing = 12
    
End With



With wrdApp
    .ListGalleries(wdBulletGallery).ListTemplates(1).Name = ""
    .Selection.Range.ListFormat.ApplyListTemplate ListTemplate:=.ListGalleries(wdBulletGallery).ListTemplates(1), _
        continuepreviouslist:=False, applyto:=wdListApplyToWholeList, defaultlistbehavior:=wdWord9ListBehavior
End With

    If LEcontentOneA <> "" Then
        wrdApp.Selection.TypeText Text:=LEcontentOneA
        wrdApp.Selection.TypeParagraph
    End If
    
    If LEcontentOneB <> "" Then
        wrdApp.Selection.TypeText Text:=LEcontentOneB
        wrdApp.Selection.TypeParagraph
    End If

    If LEcontentOneC <> "" Then
        wrdApp.Selection.TypeText Text:=LEcontentOneC
        wrdApp.Selection.TypeParagraph
    End If
    
    'end bulletted list
    wrdApp.Selection.Range.ListFormat.RemoveNumbers wdBulletGallery
    
    
'    With wrdApp.Selection.ParagraphFormat
'            .SpaceBefore = 0
'            .SpaceBeforeAuto = False
'            .SpaceAfter = 0
'            .SpaceAfterAuto = False
'            .LineSpacingRule = wdLineSpaceExactly
'            .LineSpacing = 6
'        End With
        wrdApp.Selection.TypeParagraph
        wrdApp.Selection.ParagraphFormat.LineSpacing = 12


End If


'LE POSITION TWO

If LEcityTwo <> "" And LEstateTwo <> "" Then

wrdApp.Selection.Font.Bold = True

With wrdApp.Selection
    .TypeText Text:=LEtitleTwo
    .Font.Bold = False
    
    
        LElocTwo = LEcityTwo & ", " & LEstateTwo
        .TypeText Text:=LElocTwo
    
        .ParagraphFormat.TabStops.Add Position:=lineWidth, _
            Alignment:=wdAlignTabRight, Leader:=0
        .MoveLeft Unit:=1, Count:=Len(LElocTwo)
        .TypeText Text:=vbTab
        .MoveRight Unit:=1, Count:=Len(LElocTwo)
    
        .TypeParagraph
    
        .Font.Italic = True
        .TypeText Text:=LEorgTwo
        .Font.Italic = False
        .TypeText Text:=LEdateRangeTwo
        .ParagraphFormat.TabStops.Add Position:=lineWidth, _
            Alignment:=wdAlignTabRight, Leader:=0
        .MoveLeft Unit:=1, Count:=Len(LEdateRangeTwo)
        .TypeText Text:=vbTab
        .MoveRight Unit:=1, Count:=Len(LEdateRangeTwo)
        .TypeParagraph
        
        With .ParagraphFormat
            .SpaceBefore = 0
            .SpaceBeforeAuto = False
            .SpaceAfter = 0
            .SpaceAfterAuto = False
            .LineSpacingRule = wdLineSpaceExactly
            .LineSpacing = 6
        End With
        
        .TypeParagraph
        .ParagraphFormat.LineSpacing = 12
    
End With

With wrdApp
    .ListGalleries(wdBulletGallery).ListTemplates(1).Name = ""
    .Selection.Range.ListFormat.ApplyListTemplate ListTemplate:=.ListGalleries(wdBulletGallery).ListTemplates(1), _
        continuepreviouslist:=False, applyto:=wdListApplyToWholeList, defaultlistbehavior:=wdWord9ListBehavior
End With

    If LEcontentTwoA <> "" Then
        wrdApp.Selection.TypeText Text:=LEcontentTwoA
        wrdApp.Selection.TypeParagraph
    End If
    
    If LEcontentTwoB <> "" Then
        wrdApp.Selection.TypeText Text:=LEcontentTwoB
        wrdApp.Selection.TypeParagraph
    End If

    If LEcontentTwoC <> "" Then
        wrdApp.Selection.TypeText Text:=LEcontentTwoC
        wrdApp.Selection.TypeParagraph
    End If
    
    'end bulletted list
    wrdApp.Selection.Range.ListFormat.RemoveNumbers wdBulletGallery
    wrdApp.Selection.TypeParagraph


End If



'LE POSITION THREE

If LEcityThree <> "" And LEstateThree <> "" Then

wrdApp.Selection.Font.Bold = True

With wrdApp.Selection
    .TypeText Text:=LEtitleThree
    .Font.Bold = False
    
    
        LElocThree = LEcityThree & ", " & LEstateThree
        .TypeText Text:=LElocThree
    
        .ParagraphFormat.TabStops.Add Position:=lineWidth, _
            Alignment:=wdAlignTabRight, Leader:=0
        .MoveLeft Unit:=1, Count:=Len(LElocThree)
        .TypeText Text:=vbTab
        .MoveRight Unit:=1, Count:=Len(LElocThree)
    
        .TypeParagraph
    
        .Font.Italic = True
        .TypeText Text:=LEorgThree
        .Font.Italic = False
        .TypeText Text:=LEdateRangeThree
        .ParagraphFormat.TabStops.Add Position:=lineWidth, _
            Alignment:=wdAlignTabRight, Leader:=0
        .MoveLeft Unit:=1, Count:=Len(LEdateRangeThree)
        .TypeText Text:=vbTab
        .MoveRight Unit:=1, Count:=Len(LEdateRangeThree)
        .TypeParagraph
        With .ParagraphFormat
            .SpaceBefore = 0
            .SpaceBeforeAuto = False
            .SpaceAfter = 0
            .SpaceAfterAuto = False
            .LineSpacingRule = wdLineSpaceExactly
            .LineSpacing = 6
        End With
        
        .TypeParagraph
        .ParagraphFormat.LineSpacing = 12
    
    
End With

With wrdApp
    .ListGalleries(wdBulletGallery).ListTemplates(1).Name = ""
    .Selection.Range.ListFormat.ApplyListTemplate ListTemplate:=.ListGalleries(wdBulletGallery).ListTemplates(1), _
        continuepreviouslist:=False, applyto:=wdListApplyToWholeList, defaultlistbehavior:=wdWord9ListBehavior
End With

    If LEcontentThreeA <> "" Then
        wrdApp.Selection.TypeText Text:=LEcontentThreeA
        wrdApp.Selection.TypeParagraph
    End If
    
    If LEcontentThreeB <> "" Then
        wrdApp.Selection.TypeText Text:=LEcontentThreeB
        wrdApp.Selection.TypeParagraph
    End If

    If LEcontentThreeC <> "" Then
        wrdApp.Selection.TypeText Text:=LEcontentThreeC
        wrdApp.Selection.TypeParagraph
    End If
    
    'end bulletted list
    wrdApp.Selection.Range.ListFormat.RemoveNumbers wdBulletGallery
    wrdApp.Selection.TypeParagraph

End If


'LE POSITION FOUR

If LEcityFour <> "" And LEstateFour <> "" Then

wrdApp.Selection.Font.Bold = True

With wrdApp.Selection
    .TypeText Text:=LEtitleFour
    .Font.Bold = False
    
    
        LElocFour = LEcityFour & ", " & LEstateFour
        .TypeText Text:=LElocFour
    
        .ParagraphFormat.TabStops.Add Position:=lineWidth, _
            Alignment:=wdAlignTabRight, Leader:=0
        .MoveLeft Unit:=1, Count:=Len(LElocFour)
        .TypeText Text:=vbTab
        .MoveRight Unit:=1, Count:=Len(LElocFour)
    
        .TypeParagraph
    
        .Font.Italic = True
        .TypeText Text:=LEorgFour
        .Font.Italic = False
        .TypeText Text:=LEdateRangeFour
        .ParagraphFormat.TabStops.Add Position:=lineWidth, _
            Alignment:=wdAlignTabRight, Leader:=0
        .MoveLeft Unit:=1, Count:=Len(LEdateRangeFour)
        .TypeText Text:=vbTab
        .MoveRight Unit:=1, Count:=Len(LEdateRangeFour)
        .TypeParagraph
        With .ParagraphFormat
            .SpaceBefore = 0
            .SpaceBeforeAuto = False
            .SpaceAfter = 0
            .SpaceAfterAuto = False
            .LineSpacingRule = wdLineSpaceExactly
            .LineSpacing = 6
        End With
        
        .TypeParagraph
        .ParagraphFormat.LineSpacing = 12
    
    
    
End With

With wrdApp
    .ListGalleries(wdBulletGallery).ListTemplates(1).Name = ""
    .Selection.Range.ListFormat.ApplyListTemplate ListTemplate:=.ListGalleries(wdBulletGallery).ListTemplates(1), _
        continuepreviouslist:=False, applyto:=wdListApplyToWholeList, defaultlistbehavior:=wdWord9ListBehavior
End With

    If LEcontentFourA <> "" Then
        wrdApp.Selection.TypeText Text:=LEcontentFourA
        wrdApp.Selection.TypeParagraph
    End If
    
    If LEcontentFourB <> "" Then
        wrdApp.Selection.TypeText Text:=LEcontentFourB
        wrdApp.Selection.TypeParagraph
    End If

    If LEcontentFourC <> "" Then
        wrdApp.Selection.TypeText Text:=LEcontentFourC
        wrdApp.Selection.TypeParagraph
    End If
    
    'end bulletted list
    wrdApp.Selection.Range.ListFormat.RemoveNumbers wdBulletGallery
    wrdApp.Selection.TypeParagraph


End If







'PROFESSIONAL EXPERIENCE

With wrdApp.Selection
    .Font.Bold = True
    .TypeText Text:=UCase(wsData.Range("secTwoTitle"))
    'center
    With .ParagraphFormat
        .Alignment = 1
        .SpaceAfter = 0
    End With
End With
    


'add line
With wrdApp.Selection
    .Characters(1).Borders.Enable = True
    With .ParagraphFormat
        .Borders(wdBorderBottom).lineWidth = wdLineWidth025pt
        .Borders(wdBorderTop).LineStyle = wdLineStyleNone
        .Borders(wdBorderRight).LineStyle = wdLineStyleNone
        .Borders(wdBorderLeft).LineStyle = wdLineStyleNone
    End With
    
    .TypeParagraph
End With

With wrdApp.Selection
    .Characters(1).Borders.Enable = False
    'align left
    .ParagraphFormat.Alignment = 0
    .Font.Size = 10
End With





'store variables
PEtitleOne = Range("PEtitleOne")
PEorgOne = Range("PEorgOne")
PEcityOne = Range("PEcityOne")
PEstateOne = Range("PEstateOne")
PEstartMoOne = Range("PEstartMoOne")
PEstartYrOne = Range("PEstartYrOne")
PEendMoOne = Range("PEendMoOne")
PEendYrOne = Range("PEendYrOne")
PEcontentOneA = Range("PEcontentOneA")
PEcontentOneB = Range("PEcontentOneB")
PEcontentOneC = Range("PEcontentOneC")

PEtitleTwo = Range("PEtitleTwo")
PEorgTwo = Range("PEorgTwo")
PEcityTwo = Range("PEcityTwo")
PEstateTwo = Range("PEstateTwo")
PEstartMoTwo = Range("PEstartMoTwo")
PEstartYrTwo = Range("PEstartYrTwo")
PEendMoTwo = Range("PEendMoTwo")
PEendYrTwo = Range("PEendYrTwo")
PEcontentTwoA = Range("PEcontentTwoA")
PEcontentTwoB = Range("PEcontentTwoB")
PEcontentTwoC = Range("PEcontentTwoC")

PEtitleThree = Range("PEtitleThree")
PEorgThree = Range("PEorgThree")
PEcityThree = Range("PEcityThree")
PEstateThree = Range("PEstateThree")
PEstartMoThree = Range("PEstartMoThree")
PEstartYrThree = Range("PEstartYrThree")
PEendMoThree = Range("PEendMoThree")
PEendYrThree = Range("PEendYrThree")
PEcontentThreeA = Range("PEcontentThreeA")
PEcontentThreeB = Range("PEcontentThreeB")
PEcontentThreeC = Range("PEcontentThreeC")

PEtitleFour = Range("PEtitleFour")
PEorgFour = Range("PEorgFour")
PEcityFour = Range("PEcityFour")
PEstateFour = Range("PEstateFour")
PEstartMoFour = Range("PEstartMoFour")
PEstartYrFour = Range("PEstartYrFour")
PEendMoFour = Range("PEendMoFour")
PEendYrFour = Range("PEendYrFour")
PEcontentFourA = Range("PEcontentFourA")
PEcontentFourB = Range("PEcontentFourB")
PEcontentFourC = Range("PEcontentFourC")

If PEstartMoOne <> "" Or _
    PEstartYrOne <> "" Or _
    PEendMoOne <> "" Or _
    PEendYrOne <> "" Then
        PEdateRangeOne = PEstartMoOne & " " & PEstartYrOne & " - " & PEendMoOne
        If PEendYrOne <> "" Then PEdateRangeOne = PEdateRangeOne & " " & PEendYrOne
End If

If PEstartMoTwo <> "" Or _
    PEstartYrTwo <> "" Or _
    PEendMoTwo <> "" Or _
    PEendYrTwo <> "" Then
        PEdateRangeTwo = PEstartMoTwo & " " & PEstartYrTwo & " - " & PEendMoTwo
        If PEendYrTwo <> "" Then PEdateRangeTwo = PEdateRangeTwo & " " & PEendYrTwo
End If

If PEstartMoThree <> "" Or _
    PEstartYrThree <> "" Or _
    PEendMoThree <> "" Or _
    PEendYrThree <> "" Then
        PEdateRangeThree = PEstartMoThree & " " & PEstartYrThree & " - " & PEendMoThree
        If PEendYrThree <> "" Then PEdateRangeThree = PEdateRangeThree & " " & PEendYrThree
End If

If PEstartMoFour <> "" Or _
    PEstartYrFour <> "" Or _
    PEendMoFour <> "" Or _
    PEendYrFour <> "" Then
        PEdateRangeFour = PEstartMoFour & " " & PEstartYrFour & " - " & PEendMoFour
        If PEendYrFour <> "" Then PEdateRangeFour = PEdateRangeFour & " " & PEendYrFour
End If

'PE POSITION ONE

If PEcityOne <> "" And PEstateOne <> "" Then

With wrdApp.Selection
    .TypeText Text:=PEtitleOne
    .Font.Bold = False
    
    
        PElocOne = PEcityOne & ", " & PEstateOne
        .TypeText Text:=PElocOne
    
    
        .ParagraphFormat.TabStops.Add Position:=lineWidth, _
            Alignment:=wdAlignTabRight, Leader:=0
        .MoveLeft Unit:=1, Count:=Len(PElocOne)
        .TypeText Text:=vbTab
        .MoveRight Unit:=1, Count:=Len(PElocOne)
    
        .TypeParagraph
    
        .Font.Italic = True
        .TypeText Text:=PEorgOne
        .Font.Italic = False
        .TypeText Text:=PEdateRangeOne
        .ParagraphFormat.TabStops.Add Position:=lineWidth, _
            Alignment:=wdAlignTabRight, Leader:=0
        .MoveLeft Unit:=1, Count:=Len(PEdateRangeOne)
        .TypeText Text:=vbTab
        .MoveRight Unit:=1, Count:=Len(PEdateRangeOne)
        .TypeParagraph
        With .ParagraphFormat
            .SpaceBefore = 0
            .SpaceBeforeAuto = False
            .SpaceAfter = 0
            .SpaceAfterAuto = False
            .LineSpacingRule = wdLineSpaceExactly
            .LineSpacing = 6
        End With
        
        .TypeParagraph
        .ParagraphFormat.LineSpacing = 12
    
    
End With

With wrdApp
    .ListGalleries(wdBulletGallery).ListTemplates(1).Name = ""
    .Selection.Range.ListFormat.ApplyListTemplate ListTemplate:=.ListGalleries(wdBulletGallery).ListTemplates(1), _
        continuepreviouslist:=False, applyto:=wdListApplyToWholeList, defaultlistbehavior:=wdWord9ListBehavior
End With

    If PEcontentOneA <> "" Then
        wrdApp.Selection.TypeText Text:=PEcontentOneA
        wrdApp.Selection.TypeParagraph
    End If
    
    If PEcontentOneB <> "" Then
        wrdApp.Selection.TypeText Text:=PEcontentOneB
        wrdApp.Selection.TypeParagraph
    End If

    If PEcontentOneC <> "" Then
        wrdApp.Selection.TypeText Text:=PEcontentOneC
        wrdApp.Selection.TypeParagraph
    End If
    
    'end bulletted list
    wrdApp.Selection.Range.ListFormat.RemoveNumbers wdBulletGallery
    wrdApp.Selection.TypeParagraph


End If


'PE POSITION TWO

If PEcityTwo <> "" And PEstateTwo <> "" Then

wrdApp.Selection.Font.Bold = True

With wrdApp.Selection
    .TypeText Text:=PEtitleTwo
    .Font.Bold = False
    
    
        PElocTwo = PEcityTwo & ", " & PEstateTwo
        .TypeText Text:=PElocTwo
    
        .ParagraphFormat.TabStops.Add Position:=lineWidth, _
            Alignment:=wdAlignTabRight, Leader:=0
        .MoveLeft Unit:=1, Count:=Len(PElocTwo)
        .TypeText Text:=vbTab
        .MoveRight Unit:=1, Count:=Len(PElocTwo)
    
        .TypeParagraph
    
        .Font.Italic = True
        .TypeText Text:=PEorgTwo
        .Font.Italic = False
        .TypeText Text:=PEdateRangeTwo
        .ParagraphFormat.TabStops.Add Position:=lineWidth, _
            Alignment:=wdAlignTabRight, Leader:=0
        .MoveLeft Unit:=1, Count:=Len(PEdateRangeTwo)
        .TypeText Text:=vbTab
        .MoveRight Unit:=1, Count:=Len(PEdateRangeTwo)
        .TypeParagraph
        With .ParagraphFormat
            .SpaceBefore = 0
            .SpaceBeforeAuto = False
            .SpaceAfter = 0
            .SpaceAfterAuto = False
            .LineSpacingRule = wdLineSpaceExactly
            .LineSpacing = 6
        End With
        
        .TypeParagraph
        .ParagraphFormat.LineSpacing = 12
    
End With

With wrdApp
    .ListGalleries(wdBulletGallery).ListTemplates(1).Name = ""
    .Selection.Range.ListFormat.ApplyListTemplate ListTemplate:=.ListGalleries(wdBulletGallery).ListTemplates(1), _
        continuepreviouslist:=False, applyto:=wdListApplyToWholeList, defaultlistbehavior:=wdWord9ListBehavior
End With

    If PEcontentTwoA <> "" Then
        wrdApp.Selection.TypeText Text:=PEcontentTwoA
        wrdApp.Selection.TypeParagraph
    End If
    
    If PEcontentTwoB <> "" Then
        wrdApp.Selection.TypeText Text:=PEcontentTwoB
        wrdApp.Selection.TypeParagraph
    End If

    If PEcontentTwoC <> "" Then
        wrdApp.Selection.TypeText Text:=PEcontentTwoC
        wrdApp.Selection.TypeParagraph
    End If
    
    'end bulletted list
    wrdApp.Selection.Range.ListFormat.RemoveNumbers wdBulletGallery
    wrdApp.Selection.TypeParagraph


End If



'PE POSITION THREE

If PEcityThree <> "" And PEstateThree <> "" Then

wrdApp.Selection.Font.Bold = True

With wrdApp.Selection
    .TypeText Text:=PEtitleThree
    .Font.Bold = False
    
    
        PElocThree = PEcityThree & ", " & PEstateThree
        .TypeText Text:=PElocThree
    
        .ParagraphFormat.TabStops.Add Position:=lineWidth, _
            Alignment:=wdAlignTabRight, Leader:=0
        .MoveLeft Unit:=1, Count:=Len(PElocThree)
        .TypeText Text:=vbTab
        .MoveRight Unit:=1, Count:=Len(PElocThree)
    
        .TypeParagraph
    
        .Font.Italic = True
        .TypeText Text:=PEorgThree
        .Font.Italic = False
        .TypeText Text:=PEdateRangeThree
        .ParagraphFormat.TabStops.Add Position:=lineWidth, _
            Alignment:=wdAlignTabRight, Leader:=0
        .MoveLeft Unit:=1, Count:=Len(PEdateRangeThree)
        .TypeText Text:=vbTab
        .MoveRight Unit:=1, Count:=Len(PEdateRangeThree)
        .TypeParagraph
        With .ParagraphFormat
            .SpaceBefore = 0
            .SpaceBeforeAuto = False
            .SpaceAfter = 0
            .SpaceAfterAuto = False
            .LineSpacingRule = wdLineSpaceExactly
            .LineSpacing = 6
        End With
        
        .TypeParagraph
        .ParagraphFormat.LineSpacing = 12
    
    
End With

With wrdApp
    .ListGalleries(wdBulletGallery).ListTemplates(1).Name = ""
    .Selection.Range.ListFormat.ApplyListTemplate ListTemplate:=.ListGalleries(wdBulletGallery).ListTemplates(1), _
        continuepreviouslist:=False, applyto:=wdListApplyToWholeList, defaultlistbehavior:=wdWord9ListBehavior
End With

    If PEcontentThreeA <> "" Then
        wrdApp.Selection.TypeText Text:=PEcontentThreeA
        wrdApp.Selection.TypeParagraph
    End If
    
    If PEcontentThreeB <> "" Then
        wrdApp.Selection.TypeText Text:=PEcontentThreeB
        wrdApp.Selection.TypeParagraph
    End If

    If PEcontentThreeC <> "" Then
        wrdApp.Selection.TypeText Text:=PEcontentThreeC
        wrdApp.Selection.TypeParagraph
    End If
    
    'end bulletted list
    wrdApp.Selection.Range.ListFormat.RemoveNumbers wdBulletGallery
    wrdApp.Selection.TypeParagraph

End If


'PE POSITION FOUR

If PEcityFour <> "" And PEstateFour <> "" Then

wrdApp.Selection.Font.Bold = True

With wrdApp.Selection
    .TypeText Text:=PEtitleFour
    .Font.Bold = False
    
    
        PElocFour = PEcityFour & ", " & PEstateFour
        .TypeText Text:=PElocFour
    
        .ParagraphFormat.TabStops.Add Position:=lineWidth, _
            Alignment:=wdAlignTabRight, Leader:=0
        .MoveLeft Unit:=1, Count:=Len(PElocFour)
        .TypeText Text:=vbTab
        .MoveRight Unit:=1, Count:=Len(PElocFour)
    
        .TypeParagraph
    
        .Font.Italic = True
        .TypeText Text:=PEorgFour
        .Font.Italic = False
        .TypeText Text:=PEdateRangeFour
        .ParagraphFormat.TabStops.Add Position:=lineWidth, _
            Alignment:=wdAlignTabRight, Leader:=0
        .MoveLeft Unit:=1, Count:=Len(PEdateRangeFour)
        .TypeText Text:=vbTab
        .MoveRight Unit:=1, Count:=Len(PEdateRangeFour)
        .TypeParagraph
        With .ParagraphFormat
            .SpaceBefore = 0
            .SpaceBeforeAuto = False
            .SpaceAfter = 0
            .SpaceAfterAuto = False
            .LineSpacingRule = wdLineSpaceExactly
            .LineSpacing = 6
        End With
        
        .TypeParagraph
        .ParagraphFormat.LineSpacing = 12
    
    
    
End With

With wrdApp
    .ListGalleries(wdBulletGallery).ListTemplates(1).Name = ""
    .Selection.Range.ListFormat.ApplyListTemplate ListTemplate:=.ListGalleries(wdBulletGallery).ListTemplates(1), _
        continuepreviouslist:=False, applyto:=wdListApplyToWholeList, defaultlistbehavior:=wdWord9ListBehavior
End With

    If PEcontentFourA <> "" Then
        wrdApp.Selection.TypeText Text:=PEcontentFourA
        wrdApp.Selection.TypeParagraph
    End If
    
    If PEcontentFourB <> "" Then
        wrdApp.Selection.TypeText Text:=PEcontentFourB
        wrdApp.Selection.TypeParagraph
    End If

    If PEcontentFourC <> "" Then
        wrdApp.Selection.TypeText Text:=PEcontentFourC
        wrdApp.Selection.TypeParagraph
    End If
    
    'end bulletted list
    wrdApp.Selection.Range.ListFormat.RemoveNumbers wdBulletGallery
    wrdApp.Selection.TypeParagraph

End If








'SKILLS & INTERESTS (SECTION C)

listTitleOne = Range("listTitleOne")
listTitleTwo = Range("listTitleTwo")
listTitleThree = Range("listTitleThree")
listTitleFour = Range("listTitleFour")
listTitleFive = Range("listTitleFive")
listTitleSix = Range("listTitleSix")
listTitleSeven = Range("listTitleSeven")

listOne = Range("listOne")
listTwo = Range("listTwo")
listThree = Range("listThree")
listFour = Range("listFour")
listFive = Range("listFive")
listSix = Range("listSix")
listSeven = Range("listSeven")

With wrdApp.Selection
    .Font.Bold = True
    .TypeText Text:=UCase(wsData.Range("secThreeTitle"))
    'center
    With .ParagraphFormat
        .Alignment = 1
        .SpaceAfter = 0
    End With
End With
    


'add line
With wrdApp.Selection
    .Characters(1).Borders.Enable = True
    With .ParagraphFormat
        .Borders(wdBorderBottom).lineWidth = wdLineWidth025pt
        .Borders(wdBorderTop).LineStyle = wdLineStyleNone
        .Borders(wdBorderRight).LineStyle = wdLineStyleNone
        .Borders(wdBorderLeft).LineStyle = wdLineStyleNone
    End With
    
    .TypeParagraph
End With

With wrdApp.Selection
    .Characters(1).Borders.Enable = False
    'align left
    .ParagraphFormat.Alignment = 0
    .Font.Size = 10
End With

'enter content
With wrdApp.Selection
    
    If listOne <> "" Then
        .Font.Bold = True
        .TypeText Text:=listTitleOne & ": "
        .Font.Bold = False
        .TypeText Text:=listOne
        .TypeParagraph
    End If
    
    If listTwo <> "" Then
        .Font.Bold = True
        .TypeText Text:=listTitleTwo & ": "
        .Font.Bold = False
        .TypeText Text:=listTwo
        .TypeParagraph
    End If
    
    If listThree <> "" Then
        .Font.Bold = True
        .TypeText Text:=listTitleThree & ": "
        .Font.Bold = False
        .TypeText Text:=listThree
        .TypeParagraph
    End If
    
    If listFour <> "" Then
        .Font.Bold = True
        .TypeText Text:=listTitleFour & ": "
        .Font.Bold = False
        .TypeText Text:=listFour
        .TypeParagraph
    End If
    
    If listFive <> "" Then
        .Font.Bold = True
        .TypeText Text:=listTitleFive & ": "
        .Font.Bold = False
        .TypeText Text:=listFive
        .TypeParagraph
    End If
    
    If listSix <> "" Then
        .Font.Bold = True
        .TypeText Text:=listTitleSix & ": "
        .Font.Bold = False
        .TypeText Text:=listSix
        .TypeParagraph
    End If
    
    If listSeven <> "" Then
        .Font.Bold = True
        .TypeText Text:=listTitleSeven & ": "
        .Font.Bold = False
        .TypeText Text:=listSeven
        .TypeParagraph
    End If

End With


'END OF RESUME CONTENT ****************************************************************
'MsgBox (wrdApp.Information(wdNumberOfPagesInDocument))

Do Until complete = 1

multiPageMsg = "The resume you've created is longer than one page. "
If newThru = 1 Then
    multiPageMsg = "Your resume is still over one page. "
End If

nPages = wrdDoc.ComputeStatistics(wdStatisticPages)

If nPages > 1 Then
    response = InputBox(multiPageMsg & vbNewLine & vbNewLine & _
                "Would you like to: " & vbNewLine & _
                "(A) Adjust the line spacing" & vbNewLine & _
                "(B) Leave it as is")

                
            If InStr(UCase(response), "B") > 0 Then Exit Do
            
            If InStr(UCase(response), "A") > 0 Then
                'wrdDoc.Range.End(wdUp).Select
                wrdApp.Selection.HomeKey Unit:=wdStory, Extend:=wdExtend
                wrdApp.Selection.MoveDown Unit:=wdLine, Count:=1, Extend:=wdExtend
        

                With wrdApp.Selection.ParagraphFormat
                    .SpaceAfter = 0
                    .SpaceAfterAuto = False
                    .LineSpacingRule = wdLineSpaceExactly
                    .LineSpacing = .LineSpacing - 1
                End With
            End If
                
            
Else
    complete = 1
End If
    newThru = 1
Loop

'SHOW DOCUMENT
wrdApp.Visible = True
wrdApp.Activate

'reset objects
Set wrdDoc = Nothing
Set wrdApp = Nothing

End Sub
